spring:
  application:
    name: split-service
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: 1234

app:
  jwt:
    subject: user-id
    issuer: to-sibintek-app
    secret: 12345678
    duration: 3600

logging:
  level:
    org:
      springframework:
        web:
          socket:
            config:
              WebSocketMessageBrokerStats: TRACE


server:
  port: 8080
  ssl:
    enabled: true

    key-store-type: PKCS12

    key-alias: tosibintek

    key-store: classpath:keystore.p12

    key-store-password: 123456
